### ISSUE TITLE
Use of dot_template_settings 

### ISSUE THREAD

**Issue by raiseandfall** [brainshave/broccoli-zetzer#6]
Hi @brainshave 

I couldn't have the dot_template_settings to work, so I quickly checked in the source code and it doesn't look like you are sending to zetzer.
Is that something you are planning to put in place in 3.0 ?

Thanks

**Comment by szymonrw** [comment]
Hi @raiseandfall,

Good catch! I consider it a bug since [zetzer's docs](https://github.com/brainshave/zetzer#configuration-options) mention this and other options.

Fixed in 2.0.4. Let me know if that works for you.

**Comment by raiseandfall** [comment]
Hi @brainshave,

Just updated to 2.0.4, problem fixed. Thanks !
